version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "80:3000"
    volumes: 
      - /app/node_modules # exclude and bookmark the container version of this dir
      - .:/app # map directories

# to run tests its better run : docker exec -it <container_id> npm run test
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes: 
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run", "test"]